#!/usr/bin/env bash

texmfhome=$(kpsewhich --var-value=TEXMFHOME)
cd $(dirname "${0}") > /dev/null
texnotesdir=$(pwd -L)
directories=(classes styles)

usage() {
  echo "Usage: passed without arguments (-h to get this help message)"
  echo "This script creates symlinks of files from some of the directories here to
destination : $texmfhome/tex/latex"
}

while getopts "h" flag; do
  case "${flag}" in
    h)
      usage
      exit 0
      ;;
  esac
done

if [ ! -d "$texmfhome" ]
then
  read -p "$texmfhome does not exist. mkdir? (yN) " yn
  case $yn in
      [Yy]* ) mkdir -p $texmfhome/tex/latex; echo "[+] $texmfhome created" ;;
      * ) echo "Script terminated" ; exit 0;;
  esac
else
  echo "This operation will overwrite existing files (if any) of the same name.
  destination : $texmfhome/tex/latex"
  read -p "Continue? (yN) " overwrite
  case $overwrite in
    [Yy]* ) ;;
    * ) echo "Script terminated" ; exit 0 ;;
  esac
fi

for d in ${directories[@]}; do
  for f in $texnotesdir/$d/*; do
    ln -sf "$f" $texmfhome/tex/latex/ ;
  done
done
echo "[~] symlinks established"
